services:
  auth-server:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: backend/auth-server
      dockerfile: Dockerfile
    env_file:
      - backend/auth-server/.env
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-echohub}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d echohub"]
      interval: 10s
      timeout: 5s
      retries: 5
