//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub discriminator: i32,
    pub password: String,
    pub email_verified: bool,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::oauth2_token_pairs::Entity")]
    Oauth2TokenPairs,
}

impl Related<super::oauth2_token_pairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth2TokenPairs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
